# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97f6fe1dacfcc11955a7a98ccf2bd1b5"
name = "Dhl App"
handle = "dhl-app-4"
application_url = "https://local-ensemble-develop-innovative.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tellos-development.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://local-ensemble-develop-innovative.trycloudflare.com/auth/callback",
  "https://local-ensemble-develop-innovative.trycloudflare.com/auth/shopify/callback",
  "https://local-ensemble-develop-innovative.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
